#-------------------------------
# Site Settings
title: MBA café with Angela
logo: # You can add own logo. For example '/images/logo.png'.
description: MBA面試官手把手教你怎麼準備名校MBA
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Author Settings
author:
  author__name: Angela Chen
  author__bio: 畢業於巴黎高等商學院HEC Paris，獲得超過110萬台幣獎學金。已替學校面試將近10位來自世界各地的申請者與超過十年顧問經驗。
  author__avatar: '/images/home-01.jpg'

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-facebook", link: "https://facebook.com"}
- {icon: "ion-logo-instagram", link: "https://instagram.com"}
- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
- {icon: "ion-logo-youtube", link: "https://youtube.com"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  hero__title: Hey, I’m Angela
  hero__description: 畢業於巴黎高等商學院HEC Paris，獲得超過110萬台幣獎學金。已替學校面試將近10位來自世界各地的申請者與超過十年顧問經驗，讓我幫你申請上理想的學校。
  hero__image: '/images/home-01.jpg'


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text: Subscribe here
mailchimp__button__text: Get a new tip


#-------------------------------
# Gallery Footer Section
gallery:
  gallery__title: Gallery
  gallery__columns: 3
  gallery__images:
    - alt: 'Rest'
      url: '/images/100.jpg'
    - alt: 'Lifestyle'
      url: '/images/101.jpg'
    - alt: 'Hobby'
      url: '/images/102.jpg'
    - alt: 'Notes'
      url: '/images/103.jpg'
    - alt: 'Rest'
      url: '/images/104.jpg'
    - alt: 'Hobby'
      url: '/images/105.jpg'
    - alt: 'Fashion'
      url: '/images/106.jpg'
    - alt: 'Notes'
      url: '/images/107.jpg'
    - alt: 'Rest'
      url: '/images/108.jpg'


#-------------------------------
# Contact Settings
contact:
  email: hsuanting.chen@hec.edu # Add your email for contant form
  description: Menso comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Menso theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: demo-menca # Add your shortname for Disqus Comment. For example demo-menca


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed